
version: 2
groups:
  - name: wa_zip_codes
    owner:
      name: Washington Zip Code Team
      email: zips@phdata.io

models:
    - name: wa_zip
      group: wa_zip_codes
      access: public
    - name: pre_wa_zip
      group: wa_zip_codes
      access: protected
      config:
        contract:
          enforced: true
      description: "Washington Zip Codes"
      columns:
        - name: zip_id
          data_type: number
          constraints:
            - type: not_null
            - type: unique
              warn_unenforced: false
          tests:
            - unique
        - name: zip
          data_type: varchar
          constraints:
            - type: not_null
            - type: unique
              warn_unenforced: false
          tests:
            - unique
        - name: SourceSystem
          data_type: varchar
        - name: City
          data_type: varchar
        - name: State
          data_type: varchar
